node {
  stage('========== Clone repository ==========') {
    checkout scm
  }
  stage('========== Build gradle ==========') {
    dir ('cslab') {
      withGradle {
        sh 'gradlew bootJar'
      }
    }
  }
  stage('========== Build image ==========') {
    app = docker.build("handawoon/cslab-api")
  }
  stage('========== Push image ==========') {
    docker.withRegistry('https://registry.hub.docker.com', 'dockerhub') {
      app.push("${env.BUILD_NUMBER}")
      app.push("latest")
    }
  }
}