pipeline {
    agent any
    stages {
        stage('SSH Agent Command') {
            steps {        
                sshagent (credentials: ['DBLabJenkins']) {
                sh """
                    ssh -p10022 -o StrictHostKeyChecking=no ${TARGET_HOST} '
                        export JAVA_HOME=/home/hdw/.sdkman/candidates/java/current
                        cd /home/hdw/docker.d/cslab_api
                        ./jenkins.sh
                    '
                """
                }
            }
        }
    }
    environment {
        TARGET_HOST = "hdw@dawoony.com"
    }
}
